SmartDormitory/SmartDormitory.App/Models/Notification/InboxViewComponentModel.cs
using SmartDormitory.Services.Models.Notifications;
using System.Collections.Generic;

namespace SmartDormitory.App.Models.Notification
{
    public class InboxViewComponentModel
    {
        public int UnseenCount { get; set; } = 0;

        public IEnumerable<InboxServiceModel> Notifications { get; set; }
    }
}

SmartDormitory/SmartDormitory.App/Models/Notification/InboxViewModel.cs
using SmartDormitory.Services.Models.Notifications;
using System.Collections.Generic;

namespace SmartDormitory.App.Models.Notification
{
    public class InboxViewModel
    {
        public int TotalPages { get; set; }

        public int CurrentPage { get; set; }

        public int PreviousPage => this.CurrentPage == 1
            ? 1
            : this.CurrentPage - 1;

        public int NextPage => this.CurrentPage == this.TotalPages
            ? this.TotalPages
            : this.CurrentPage + 1;

        public IEnumerable<InboxServiceModel> Notifications { get; set; }
    }
}

SmartDormitory/SmartDormitory.App/Controllers/NotificationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmartDormitory.App.Infrastructure.Extensions;
using SmartDormitory.App.Models.Notification;
using SmartDormitory.Services.Contracts;
using System;
using System.Threading.Tasks;

namespace SmartDormitory.App.Controllers
{
    [Authorize]
    public class NotificationController : Controller
    {
        private const int PageSize = 10;

        private readonly INotificationService notificationService;

        public NotificationController(INotificationService notificationService)
        {
            this.notificationService = notificationService;
        }

        [HttpGet]
        public async Task<IActionResult> Inbox(int seen = 0, int page = 1)
        {
            var userId = this.User.GetId();

            var notifications = await this.notificationService.GetAllByUserId(userId, seen, page, PageSize);
            var totalNotifications = await this.notificationService.TotalCountByCriteria(userId, seen, page, PageSize);

            var model = new InboxViewModel
            {
                CurrentPage = page,
                Notifications = notifications,
                TotalPages = (int)Math.Ceiling(totalNotifications / (double)PageSize),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            await this.notificationService.Delete(id);

            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> ReadAll()
        {
            string userId = this.User.GetId();
            await this.notificationService.ReadAll(userId);

            return RedirectToAction(nameof(Inbox), new { seen = 1 });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAllHistory()
        {
            await this.notificationService.DeleteAllHistory();

            return RedirectToAction(nameof(Inbox), new { seen = 0 });
        }
    }
}

SmartDormitory/SmartDormitory.App/Views/Notification/Inbox.cshtml
@model InboxViewModel
@{
    var seen = Context.Request.Query["seen"];
    var bodyBg = seen == "1" ? "bg-white" : "rgba-cyan-light";
    var seenDisabled = seen == "1" ? "disabled" : "";
    var unseenDisabled = seen == "0" ? "disabled" : "";
    var currentTabText = seen == "1" ? "Seen notifications" : "Unseen notifications";
}

<h1>Notifications inbox</h1>

<div class="row">
    <div class="col-md-6">
        <a asp-controller="Notification" asp-action="Inbox" asp-route-seen="0" class="btn btn-cyan btn-lg font-weight-bold @unseenDisabled">New notifications</a>
        <a asp-controller="Notification" asp-action="Inbox" asp-route-seen="1" class="btn btn-blue-grey btn-lg font-weight-bold @seenDisabled">History</a>
    </div>
    <div class="offset-md-3"></div>
    <div class="col-md-3">
        @if (seen == "0")
        {
            <form sp-controller="Notification" asp-action="ReadAll" method="post">
                <button type="submit" class="btn btn-indigo float-right">Read all</button>
            </form>
        }
        else if (seen == "1")
        { <form sp-controller="Notification" asp-action="DeleteAllHistory" method="post">
              <button type="submit" class="btn btn-indigo float-right">Delete all</button>
            </form>
        }
    </div>
</div>

<p class="display-4 text-center">@currentTabText</p>

<table id="current-user-messages" class="table table-hover table-striped mt-3">
    <thead class="thead-dark">
        <tr>
            <th class="text-center">Message</th>
            <th class="text-center">Date time</th>
            <th class="text-center">Sensor name</th>
            <th class="text-center">Alarm value</th>
            <th class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody class="@bodyBg">
        @foreach (var notif in Model.Notifications)
        {
            <tr>
                <td class="h6">@notif.Message</td>
                <td class="h6">@notif.CreatedOn</td>
                <td class="h6">@notif.SensorName</td>
                <td class="h6">@notif.AlarmValue @notif.MeasureUnit</td>
                <td>
                    <div class="row">
                        <a asp-controller="Sensor" asp-action="Details" asp-route-sensorId="@notif.SensorId" class="btn btn-sm btn-amber font-weight-bold">
                            <h3><i class="fas fa-tachometer-alt"></i></h3>
                        </a>
                        <form asp-controller="Notification" asp-action="Delete" asp-route-id="@notif.Id" method="post" data-ajax="true" data-ajax-success="deleteItem(this)">
                            <button type="submit" class="btn btn-danger">
                                <i class="far fa-trash-alt"></i>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var previousDisabled = Model.CurrentPage == 1 ? "disabled" : string.Empty;
    var nextDisabled = Model.CurrentPage == Model.TotalPages ? "disabled" : string.Empty;
}

<ul class="pagination ">
    <li class="page-item @previousDisabled">
        <a class="page-link" href="/Notification/Inbox?seen=@seen&page=@Model.PreviousPage" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
        </a>
    </li>

    @for (int i = 1; i <= Model.TotalPages; i++)
    {
        <li class="page-item @(Model.CurrentPage == i ? "active" : string.Empty)"><a class="page-link" href="/Notification/Inbox?seen=@seen&page=@i">@i</a></li>
    }

    <li class="page-item @nextDisabled">
        <a class="page-link " href="/Notification/Inbox?seen=@seen&page=@Model.NextPage" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
        </a>
    </li>
</ul>

@section Scripts {
    <script>
        function deleteItem(form) {
            $(form).parents('tr').remove()
        }
    </script>
}